package com.mediabox.findpro.data;

// Generated 2015-9-21 15:03:26 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AddressBook generated by hbm2java
 */
@Entity
@Table(name = "address_book", catalog = "findpro")
public class AddressBook implements java.io.Serializable {

	private int idaddressBook;
	private String address;
	private String userId;
	private Boolean isPrimary;
	private Boolean isBilling;

	public AddressBook() {
	}

	public AddressBook(int idaddressBook) {
		this.idaddressBook = idaddressBook;
	}

	public AddressBook(int idaddressBook, String address, String userId,
			Boolean isPrimary, Boolean isBilling) {
		this.idaddressBook = idaddressBook;
		this.address = address;
		this.userId = userId;
		this.isPrimary = isPrimary;
		this.isBilling = isBilling;
	}

	@Id
	@Column(name = "idaddress_book", unique = true, nullable = false)
	public int getIdaddressBook() {
		return this.idaddressBook;
	}

	public void setIdaddressBook(int idaddressBook) {
		this.idaddressBook = idaddressBook;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "user_id", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "is_primary")
	public Boolean getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Boolean isPrimary) {
		this.isPrimary = isPrimary;
	}

	@Column(name = "is_billing")
	public Boolean getIsBilling() {
		return this.isBilling;
	}

	public void setIsBilling(Boolean isBilling) {
		this.isBilling = isBilling;
	}

}
