package com.mediabox.findpro.data;

// Generated 2015-10-13 14:44:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "findpro")
public class Category implements java.io.Serializable {

	private int idcategory;
	private String categoryName;

	public Category() {
	}

	public Category(int idcategory) {
		this.idcategory = idcategory;
	}

	public Category(int idcategory, String categoryName) {
		this.idcategory = idcategory;
		this.categoryName = categoryName;
	}

	@Id
	@Column(name = "idcategory", unique = true, nullable = false)
	public int getIdcategory() {
		return this.idcategory;
	}

	public void setIdcategory(int idcategory) {
		this.idcategory = idcategory;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}
