package com.mediabox.findpro.data;

// Generated 2015-8-17 13:02:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private Integer idCompany;
	private String name;
	private Set employees = new HashSet(0);

	public Company() {
	}

	public Company(String name, Set employees) {
		this.name = name;
		this.employees = employees;
	}

	public Integer getIdCompany() {
		return this.idCompany;
	}

	public void setIdCompany(Integer idCompany) {
		this.idCompany = idCompany;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
