package com.mediabox.findpro.data;

// Generated 2015-8-17 13:02:21 by Hibernate Tools 4.3.1

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private Integer contactid;
	private User user;

	public Contact() {
	}

	public Contact(User user) {
		this.user = user;
	}

	public Integer getContactid() {
		return this.contactid;
	}

	public void setContactid(Integer contactid) {
		this.contactid = contactid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
