package com.mediabox.findpro.data;

// Generated 2015-8-17 13:02:21 by Hibernate Tools 4.3.1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer idEmployee;
	private Company company;
	private String name;

	public Employee() {
	}

	public Employee(Company company, String name) {
		this.company = company;
		this.name = name;
	}

	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
