package com.mediabox.findpro.data;

// Generated 2015-10-13 14:14:06 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "findpro")
public class Menu implements java.io.Serializable {

	private Integer idmenu;
	private String name;
	private String description;
	private Integer parentMenu;
	private String imageUrl;
	private Integer categoryId;

	public Menu() {
	}

	public Menu(String name, String description, Integer parentMenu,
			String imageUrl, Integer categoryId) {
		this.name = name;
		this.description = description;
		this.parentMenu = parentMenu;
		this.imageUrl = imageUrl;
		this.categoryId = categoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idmenu", unique = true, nullable = false)
	public Integer getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(Integer idmenu) {
		this.idmenu = idmenu;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "parent_menu")
	public Integer getParentMenu() {
		return this.parentMenu;
	}

	public void setParentMenu(Integer parentMenu) {
		this.parentMenu = parentMenu;
	}

	@Column(name = "image_url", length = 200)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

}
