package com.mediabox.findpro.data;

// Generated 2015-10-19 8:40:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "order_item", catalog = "findpro")
public class OrderItem implements java.io.Serializable {

	private Integer idorderItem;
	private Order order;
	private Integer menuId;
	private Integer count;
	private Long subtotal;

	public OrderItem() {
	}

	public OrderItem(Order order, Integer menuId, Integer count, Long subtotal) {
		this.order = order;
		this.menuId = menuId;
		this.count = count;
		this.subtotal = subtotal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idorder_item", unique = true, nullable = false)
	public Integer getIdorderItem() {
		return this.idorderItem;
	}

	public void setIdorderItem(Integer idorderItem) {
		this.idorderItem = idorderItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "menu_id")
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "subtotal", precision = 10, scale = 0)
	public Long getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Long subtotal) {
		this.subtotal = subtotal;
	}

}
