package com.mediabox.findpro.data;

// Generated 2015-10-17 15:02:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "findpro")
public class Payment implements java.io.Serializable {

	private Integer idpayment;
	private Boolean isPrimary;
	private String paymentType;
	private Integer userId;

	public Payment() {
	}

	public Payment(Boolean isPrimary, String paymentType, Integer userId) {
		this.isPrimary = isPrimary;
		this.paymentType = paymentType;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpayment", unique = true, nullable = false)
	public Integer getIdpayment() {
		return this.idpayment;
	}

	public void setIdpayment(Integer idpayment) {
		this.idpayment = idpayment;
	}

	@Column(name = "is_primary")
	public Boolean getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Boolean isPrimary) {
		this.isPrimary = isPrimary;
	}

	@Column(name = "payment_type", length = 45)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
