package com.mediabox.findpro.data;

// Generated 2015-8-17 13:02:21 by Hibernate Tools 4.3.1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private String idproject;
	private String projectname;
	private String status;
	private String userid;

	public Project() {
	}

	public Project(String idproject) {
		this.idproject = idproject;
	}

	public Project(String idproject, String projectname, String status,
			String userid) {
		this.idproject = idproject;
		this.projectname = projectname;
		this.status = status;
		this.userid = userid;
	}

	public String getIdproject() {
		return this.idproject;
	}

	public void setIdproject(String idproject) {
		this.idproject = idproject;
	}

	public String getProjectname() {
		return this.projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}
