package com.mediabox.findpro.data;

// Generated 2015-10-10 13:44:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "findpro")
public class Project implements java.io.Serializable {

	private String idproject;
	private String projectname;
	private String status;
	private String userid;

	public Project() {
	}

	public Project(String idproject) {
		this.idproject = idproject;
	}

	public Project(String idproject, String projectname, String status,
			String userid) {
		this.idproject = idproject;
		this.projectname = projectname;
		this.status = status;
		this.userid = userid;
	}

	@Id
	@Column(name = "idproject", unique = true, nullable = false, length = 45)
	public String getIdproject() {
		return this.idproject;
	}

	public void setIdproject(String idproject) {
		this.idproject = idproject;
	}

	@Column(name = "projectname", length = 45)
	public String getProjectname() {
		return this.projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "userid", length = 45)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}
