package com.mediabox.findpro.data;

// Generated 2015-8-17 13:02:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userid;
	private String password;
	private String username;
	private Set contacts = new HashSet(0);

	public User() {
	}

	public User(String password, String username, Set contacts) {
		this.password = password;
		this.username = username;
		this.contacts = contacts;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

}
